// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "6509bfbf1058d1bb3fd1c43272e81f7f"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"d779937177a8bb6616141958e44450c5": "1f8b08000000000000ffb491316b03310c8577ff8ab7e58e26bf2053a1194269690337640ace59170c77729064da9f5f62a7c775e9164fe67d4f427ada6cf034c58b78237457d70bdd7ee6cf23212b89bac601400c28ef1c2f4a12fdb82eb20f41481546df064e06cee32f9a52662b1591ad6a81384d40b157a57bdf7f763b34f746eb6a692bfc38ecdf9e0f47bcee8e6862685dbb757f4734f1acc3e3c754f396b52a0834f83c1a569ceca4c4b6aaa65b5ea718eead20349010f7a435c9b2c23f8b2d4ff192bed80549d7e529d07bed7da0ed92cc09ccf4270000fffff8aa5cadd3010000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "./migrations")
		b.SetResolver("001-initial.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "d779937177a8bb6616141958e44450c5"})
	}()
	return nil
}()
