// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "6509bfbf1058d1bb3fd1c43272e81f7f"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"d779937177a8bb6616141958e44450c5": "1f8b08000000000000ffb490c14a03311086ef798affd65d6c9fa027c11e8a285ad8434f32dd9996c0eea46426e8e38b8996f5e2cd9cc2f74dc23fff6683bb395e32b960b88631cbd7cde934098a49b6d00500888c7a4ef16292234deb8a89398b195c3e1c9a1c5aa61f35a7a25e5f44f5c65834cd401d6f6478debf0e3b74df1faddb48dfe4cb61ff747f38e271774417b90ffd36fc8ee899d4ceff1fd39cbc5823603953991c2b4dfe66a2befa23eeb2e087f4ae8173ba2e0bc6483612cb76696e7bddec67000000ffff09913427a9010000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "./migrations")
		b.SetResolver("001-initial.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "d779937177a8bb6616141958e44450c5"})
	}()
	return nil
}()
